"""Added DocType and PropName

Peek Plugin Database Migration Script

Revision ID: 86a7af672ecf
Revises: eb2a46442ecb
Create Date: 2018-06-17 22:45:10.336674

"""

# revision identifiers, used by Alembic.
revision = '86a7af672ecf'
down_revision = 'eb2a46442ecb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocDbDocumentType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_index('idx_DocType_name', 'DocDbDocumentType', ['name'], unique=True, schema='pl_docdb')
    op.create_index('idx_DocType_title', 'DocDbDocumentType', ['title'], unique=True, schema='pl_docdb')
    op.create_table('DocDbProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetKey', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_index('idx_DocDbProp_model_name', 'DocDbProperty', ['modelSetKey', 'name'], unique=True, schema='pl_docdb')
    op.create_index('idx_DocDbProp_model_title', 'DocDbProperty', ['modelSetKey', 'title'], unique=True, schema='pl_docdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_DocDbProp_model_title', table_name='DocDbProperty', schema='pl_docdb')
    op.drop_index('idx_DocDbProp_model_name', table_name='DocDbProperty', schema='pl_docdb')
    op.drop_table('DocDbProperty', schema='pl_docdb')
    op.drop_index('idx_DocType_title', table_name='DocDbDocumentType', schema='pl_docdb')
    op.drop_index('idx_DocType_name', table_name='DocDbDocumentType', schema='pl_docdb')
    op.drop_table('DocDbDocumentType', schema='pl_docdb')
    # ### end Alembic commands ###