"""initial tables

Peek Plugin Database Migration Script

Revision ID: eb2a46442ecb
Revises: 
Create Date: 2018-06-10 23:00:52.574110

"""

# revision identifiers, used by Alembic.
revision = 'eb2a46442ecb'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocDbModelSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('propsJson', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name'),
    schema='pl_docdb'
    )
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_table('DocDbChunkQueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_docdb.DocDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chunkKey'),
    schema='pl_docdb'
    )
    op.create_table('DocDbDocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_docdb.DocDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_index('idx_Document_gridKey', 'DocDbDocument', ['chunkKey'], unique=False, schema='pl_docdb')
    op.create_index('idx_Document_key', 'DocDbDocument', ['modelSetId', 'key'], unique=True, schema='pl_docdb')
    op.create_table('DocDbEncodedChunkTuple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('encodedData', sa.LargeBinary(), nullable=False),
    sa.Column('encodedHash', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_docdb.DocDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_index('idx_Chunk_modelSetId_chunkKey', 'DocDbEncodedChunkTuple', ['modelSetId', 'chunkKey'], unique=False, schema='pl_docdb')
    op.create_table('SettingProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settingId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('char_value', sa.String(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['settingId'], ['pl_docdb.Setting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_docdb'
    )
    op.create_index('idx_SettingProperty_settingId', 'SettingProperty', ['settingId'], unique=False, schema='pl_docdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_SettingProperty_settingId', table_name='SettingProperty', schema='pl_docdb')
    op.drop_table('SettingProperty', schema='pl_docdb')
    op.drop_index('idx_Chunk_modelSetId_chunkKey', table_name='DocDbEncodedChunkTuple', schema='pl_docdb')
    op.drop_table('DocDbEncodedChunkTuple', schema='pl_docdb')
    op.drop_index('idx_Document_key', table_name='DocDbDocument', schema='pl_docdb')
    op.drop_index('idx_Document_gridKey', table_name='DocDbDocument', schema='pl_docdb')
    op.drop_table('DocDbDocument', schema='pl_docdb')
    op.drop_table('DocDbChunkQueue', schema='pl_docdb')
    op.drop_table('Setting', schema='pl_docdb')
    op.drop_table('DocDbModelSet', schema='pl_docdb')
    # ### end Alembic commands ###